### ISSUE TITLE
Host docs on readthedocs.org

### ISSUE THREAD

**Issue by dzheng256** [ELI-Data-Mining-Group/pelitk#1]
It would be nice to write our documentation entirely in the docstrings of the code and generate documentation via [sphinx-autoapi](https://github.com/readthedocs/sphinx-autoapi) or similar, and host at https://readthedocs.org/ e.g. https://docs.scrapy.org/en/latest/

**Comment by naraehan** [comment]
That sounds like the right idea... you know better than me about this!  I'm on board.

**Comment by naraehan** [comment]
Can I will let you close these issues.

**Comment by bnaismith** [comment]
For simplicity' sake, we'll stick to the current format.

**Comment by dzheng256** [comment]
discussed offline, we'll just keep the current markdown-based format for now, readthedocs is kind of overkill for our use case
