### ISSUE TITLE
Add test coverage and CI via Travis CI

### ISSUE THREAD

**Issue by dzheng256** [ELI-Data-Mining-Group/pelitk#2]
We should add unit tests and have continuous integration testing via https://travis-ci.org/ which will run on pull requests and commits to master branch. As things are now, it is easy to break the code when committing directly to master. For example, the master branch recently contained a typo and was fixed in d69abdff102d8a87609a9fa31d5153135a11a869. Having tests and making changes via pull requests should help prevent that.

**Comment by naraehan** [comment]
Yep, good idea. Go on ahead with relevant setting changes.

**Comment by bnaismith** [comment]
Dan, can we close this issue now?

**Comment by dzheng256** [comment]
Ah yes sorry forgot to close. this is done (https://github.com/ELI-Data-Mining-Group/pelitk/pull/6)
