### ISSUE TITLE
standardize text input format, especially in adv_guiraud()

### ISSUE THREAD

**Issue by dzheng256** [ELI-Data-Mining-Group/pelitk#4]
In `adv_guiraud` it seems we currently support 3 different text data input types: 
- string
- list of strings (tokens)
- list of list of strings?

I am sure this was once useful to have, but am not sure that it makes sense to support all three of these. The code is confusing to read and it would be simpler and cleaner to just support 1 input type, perhaps a list of tokens? Then the user just needs to call `re_tokenize` outside or pass their own tokenized list to the function.

**Comment by naraehan** [comment]
I am on board with choice (2) list of strings (tokens) as the input type. But we also need to consider "ease of use" for our intended audience. Let's chat about this in our meeting.

**Comment by naraehan** [comment]
text input format: (2) list of strings (tokens) only. No string input. 
 
And, we will create a separate function that takes input: a list of strings, then returns the list without punctuation and numeric tokens removed. This will be handy for post-processing a NLTK-tokenized token list (which PELIC dataset focuses on.)
